#!/usr/bin/env bash
#
# Interactive .env file generator for local Project Wingman development.
#
# Prompts for secrets silently (no echo, not stored in shell history) and writes
# the values to `backend/.env` and `extension/.env`. Public values (URLs, OAuth
# client IDs, publishable keys) are pre-filled with sensible defaults — just
# press Enter to accept.
#
# Usage:
#   bash scripts/setup_env.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "── Project Wingman local .env setup ──"
echo

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
  # $1 = label, $2 = default value, sets var REPLY
  local label="$1"
  local default="$2"
  if [[ -n "$default" ]]; then
    read -rp "  ${label} [${default}]: " REPLY
    REPLY="${REPLY:-$default}"
  else
    read -rp "  ${label}: " REPLY
  fi
}

ask_secret() {
  # $1 = label, sets var REPLY (input hidden)
  local label="$1"
  read -rsp "  ${label} (hidden): " REPLY
  echo
}

# ── Collect values ────────────────────────────────────────────────────────────

echo "PUBLIC values (defaults are fine — press Enter to accept):"
echo

ask "Supabase URL" "https://YOUR_PROJECT.supabase.co"
SUPABASE_URL="$REPLY"

ask "Supabase publishable key (anon)" "YOUR_SUPABASE_ANON_KEY"
SUPABASE_PUBLISHABLE="$REPLY"

ask "Backend URL" "http://localhost:8000"
BACKEND_URL="$REPLY"

ask "Chrome OAuth Client ID" "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
GOOGLE_CLIENT_ID="$REPLY"

# Written to extension/.env as VITE_GOOGLE_CLIENT_ID and injected into the built
# manifest's oauth2.client_id by vite.config.ts. Without it, Google sign-in fails
# because chrome.identity.getAuthToken reads that manifest field.

ask "Google Workspace domain allowed to sign in (blank = any)" ""
ALLOWED_DOMAIN="$REPLY"

echo
echo "SECRET values (input hidden — paste at the prompt):"
echo

ask_secret "Supabase secret key (sb_secret_…)"
SUPABASE_SECRET="$REPLY"

ask_secret "OpenRouter API key (sk-or-v1-…)"
OPENROUTER_API_KEY="$REPLY"

# ── Write backend/.env ────────────────────────────────────────────────────────

BACKEND_ENV="${REPO_ROOT}/backend/.env"
cat > "$BACKEND_ENV" <<EOF
# Generated by scripts/setup_env.sh
# DO NOT COMMIT — contains secret keys.

# ── Supabase ──────────────────────────────────────────────────────────────────
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SUPABASE_SECRET}

# ── LLM providers ─────────────────────────────────────────────────────────────
# Only OpenRouter is wired for local dev. Others remain empty; their dispatch
# returns 503 from /api/v1/llm/* if hit.
ANTHROPIC_API_KEY=
GEMINI_API_KEY=
GROQ_API_KEY=
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
OPENROUTER_REFERER=https://clientlens.example.com
OPENROUTER_TITLE=Project Wingman

# ── Pinecone — intentionally empty (init skipped, embeddings stubbed) ─────────
PINECONE_API_KEY=
PINECONE_INDEX=clientlens

# ── Google OAuth (needed for Slides/Docs/Drive + Calendar; client secret only
#    for the server-side flows, leave blank if you are not using them) ──
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=

# ── App ───────────────────────────────────────────────────────────────────────
BACKEND_URL=${BACKEND_URL}
ALLOWED_ORIGINS=["chrome-extension://","http://localhost:3000"]
JWT_SECRET=local-dev-only-not-used
EOF

chmod 600 "$BACKEND_ENV"
echo "✓ wrote $BACKEND_ENV"

# ── Write extension/.env ──────────────────────────────────────────────────────

EXT_ENV="${REPO_ROOT}/extension/.env"
cat > "$EXT_ENV" <<EOF
# Generated by scripts/setup_env.sh
# DO NOT COMMIT.

# ── Mock mode off for real backend testing ────────────────────────────────────
VITE_MOCK_MODE=false

# ── Default LLM provider (OpenRouter via backend proxy) ───────────────────────
VITE_LLM_PROVIDER=openrouter
VITE_OPENROUTER_MODEL=openai/gpt-oss-20b:free

# ── Backend ───────────────────────────────────────────────────────────────────
# vite.config.ts also derives a host_permissions entry from this on https URLs,
# replacing the your-backend.railway.app placeholder in the built manifest.
VITE_BACKEND_URL=${BACKEND_URL}

# ── Google sign-in ────────────────────────────────────────────────────────────
# Injected into the built manifest as oauth2.client_id. chrome.identity
# .getAuthToken reads it from there, so sign-in breaks if this is unset.
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
VITE_ALLOWED_DOMAIN=${ALLOWED_DOMAIN}

# ── Supabase ──────────────────────────────────────────────────────────────────
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${SUPABASE_PUBLISHABLE}

# ── Meeting copilot off for first run (no Deepgram / Zoho) ────────────────────
VITE_MEETING_COPILOT=false
VITE_STT_PROVIDER=mock

# ── Preset keys empty — extension never holds provider keys ───────────────────
VITE_GEMINI_PRESET_KEY=
VITE_GROQ_PRESET_KEY=
EOF

chmod 600 "$EXT_ENV"
echo "✓ wrote $EXT_ENV"

echo
echo "── Done ──"
echo "  backend/.env     ${BACKEND_ENV}"
echo "  extension/.env   ${EXT_ENV}"
echo
echo "Next:"
echo "  1. Start backend:   cd backend && pip install -r requirements.txt && uvicorn main:app --reload"
echo "  2. Build extension: cd extension && npm install && npm run dev"
echo "  3. Load in Chrome:  chrome://extensions → Developer mode ON → Load unpacked → extension/dist/"
echo
echo "You do NOT need to hand-edit extension/manifest.json. The build injects your"
echo "OAuth client ID and backend host into extension/dist/manifest.json from the"
echo ".env files above. Verify with: bash scripts/lint-manifest.sh"
