#!/usr/bin/env bash
#
# Interactive .env file generator for local Project Wingman development.
#
# Prompts for secrets silently (no echo, not stored in shell history) and writes
# the values to `backend/.env` and `extension/.env`. Public values (URLs, OAuth
# client IDs, publishable keys) are pre-filled with sensible defaults, just
# press Enter to accept.
#
# Usage:
#   bash scripts/setup_env.sh                    interactive
#   bash scripts/setup_env.sh --non-interactive  defaults only, secrets left blank
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# With `set -e`, a `read` against a closed stdin aborts the script on the first
# prompt and writes nothing, which looks like a silent crash. That happens in CI,
# in Docker builds, and any time stdin is closed.
#
# The fix is to handle EOF rather than to stop prompting, so that piping answers
# in still works: `printf 'a\nb\n' | bash scripts/setup_env.sh`. Only
# --non-interactive skips the prompts outright and takes every default.
INTERACTIVE=1
for arg in "$@"; do
  [[ "$arg" == "--non-interactive" ]] && INTERACTIVE=0
done

echo "── Project Wingman local .env setup ──"
echo
if (( ! INTERACTIVE )); then
  echo "Running with --non-interactive: public values get their defaults and every"
  echo "secret is left blank. Fill the blanks in before starting the backend."
  echo
fi

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
  # $1 = label, $2 = default value, sets var REPLY
  local label="$1"
  local default="$2"
  if (( ! INTERACTIVE )); then
    REPLY="$default"
    return
  fi
  if [[ -n "$default" ]]; then
    # `if ! read` keeps `set -e` from killing the script when stdin hits EOF.
    if ! read -rp "  ${label} [${default}]: " REPLY; then
      REPLY=""
      echo
    fi
    REPLY="${REPLY:-$default}"
  else
    if ! read -rp "  ${label}: " REPLY; then
      REPLY=""
      echo
    fi
  fi
}

ask_secret() {
  # $1 = label, sets var REPLY (input hidden)
  local label="$1"
  if (( ! INTERACTIVE )); then
    REPLY=""
    return
  fi
  if ! read -rsp "  ${label} (hidden): " REPLY; then
    REPLY=""
  fi
  echo
}

# ── Collect values ────────────────────────────────────────────────────────────

echo "PUBLIC values (defaults are fine: press Enter to accept):"
echo

ask "Supabase URL" "https://YOUR_PROJECT.supabase.co"
SUPABASE_URL="$REPLY"

ask "Supabase publishable key (anon)" "YOUR_SUPABASE_ANON_KEY"
SUPABASE_PUBLISHABLE="$REPLY"

ask "Backend URL" "http://localhost:8000"
BACKEND_URL="$REPLY"

# OPTIONAL. Only Google Slides/Docs/Drive export and Calendar sync use
# chrome.identity.getAuthToken, which reads this from the built manifest. It is
# NOT needed to sign in (v1.0 provisions a local admin user) and not needed for
# Zoho. Press Enter to skip; the rest of the product works without it.
echo "  (optional, press Enter to skip: only needed for Google Slides/Drive export"
echo "   and Calendar sync)"
ask "Chrome OAuth Client ID" ""
GOOGLE_CLIENT_ID="$REPLY"

# Used to infer the rep's own company domain for team config. It does NOT gate
# sign-in, despite what earlier docs claimed.
ask "Your company domain (used for team config, blank = example.com)" ""
ALLOWED_DOMAIN="$REPLY"

echo
echo "SECRET values (input hidden: paste at the prompt):"
echo

ask_secret "Supabase secret key (sb_secret_…)"
SUPABASE_SECRET="$REPLY"

ask_secret "OpenRouter API key (sk-or-v1-…)"
OPENROUTER_API_KEY="$REPLY"

# ── Write backend/.env ────────────────────────────────────────────────────────

BACKEND_ENV="${REPO_ROOT}/backend/.env"
cat > "$BACKEND_ENV" <<EOF
# Generated by scripts/setup_env.sh
# DO NOT COMMIT: contains secret keys.

# ── Supabase ──────────────────────────────────────────────────────────────────
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SUPABASE_SECRET}

# ── LLM providers ─────────────────────────────────────────────────────────────
# Only OpenRouter is wired for local dev. Others remain empty; their dispatch
# returns 503 from /api/v1/llm/* if hit.
ANTHROPIC_API_KEY=
GEMINI_API_KEY=
GROQ_API_KEY=
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
OPENROUTER_REFERER=https://project-wingman.example.com
OPENROUTER_TITLE=Project Wingman

# ── Pinecone: intentionally empty (init skipped, embeddings stubbed) ─────────
PINECONE_API_KEY=
PINECONE_INDEX=clientlens

# ── Google OAuth (currently UNUSED by the backend) ────────────────────────────
# These two settings exist in config.py but are read by no backend code. All
# Google auth is client-side: Slides/Docs/Drive export and Calendar sync call
# chrome.identity.getAuthToken(), which reads oauth2.client_id from the built
# manifest (set VITE_GOOGLE_CLIENT_ID in extension/.env instead). Reserved for a
# future server-side Google flow; leaving them blank changes nothing today.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ── App ───────────────────────────────────────────────────────────────────────
BACKEND_URL=${BACKEND_URL}
ALLOWED_ORIGINS=["chrome-extension://","http://localhost:3000"]
JWT_SECRET=local-dev-only-not-used

# ── Auth ──────────────────────────────────────────────────────────────────────
# REQUIRED for v1.0 to function at all. Nothing in the extension creates a
# Supabase session (signInWithGoogle exists but is never called), so with
# dev_mode off, AuthMiddleware rejects every request and no LLM call succeeds.
#
# The consequence: this backend accepts every request as a stub sales_rep user
# (admin endpoints stay gated). Bind it to localhost or keep it behind your own
# network boundary. Do NOT deploy it to a public URL in this configuration.
DEV_MODE=true
EOF

chmod 600 "$BACKEND_ENV"
echo "✓ wrote $BACKEND_ENV"

# ── Write extension/.env ──────────────────────────────────────────────────────

EXT_ENV="${REPO_ROOT}/extension/.env"
cat > "$EXT_ENV" <<EOF
# Generated by scripts/setup_env.sh
# DO NOT COMMIT.

# ── Mock mode off for real backend testing ────────────────────────────────────
VITE_MOCK_MODE=false

# ── Default LLM provider (OpenRouter via backend proxy) ───────────────────────
VITE_LLM_PROVIDER=openrouter
VITE_OPENROUTER_MODEL=openai/gpt-oss-20b:free

# ── Backend ───────────────────────────────────────────────────────────────────
# vite.config.ts also derives a host_permissions entry from this on https URLs,
# replacing the your-backend.railway.app placeholder in the built manifest.
VITE_BACKEND_URL=${BACKEND_URL}

# ── Auth ──────────────────────────────────────────────────────────────────────
# Must match DEV_MODE in backend/.env. Sends a stub bearer token instead of a
# Supabase JWT. Required in v1.0: no code path creates a Supabase session.
VITE_DEV_MODE=true

# ── Google (optional) ─────────────────────────────────────────────────────────
# Injected into the built manifest as oauth2.client_id. Only Slides/Docs/Drive
# export and Calendar sync need it. Blank is fine.
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# Company domain for team config. Does not gate sign-in.
VITE_ALLOWED_DOMAIN=${ALLOWED_DOMAIN}

# ── Supabase ──────────────────────────────────────────────────────────────────
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${SUPABASE_PUBLISHABLE}

# ── Meeting copilot off for first run (no Deepgram / Zoho) ────────────────────
VITE_MEETING_COPILOT=false
VITE_STT_PROVIDER=mock

# ── Preset keys empty: extension never holds provider keys ───────────────────
VITE_GEMINI_PRESET_KEY=
VITE_GROQ_PRESET_KEY=
EOF

chmod 600 "$EXT_ENV"
echo "✓ wrote $EXT_ENV"

echo
echo "── Done ──"
if true; then
  MISSING=()
  while IFS= read -r line; do
    [[ "$line" =~ ^([A-Z_]+)=$ ]] && MISSING+=("${BASH_REMATCH[1]}")
  done < "$BACKEND_ENV"
  if (( ${#MISSING[@]} )); then
    echo "  Still blank in backend/.env: ${MISSING[*]}"
  fi
fi
echo "  backend/.env     ${BACKEND_ENV}"
echo "  extension/.env   ${EXT_ENV}"
echo
echo "Next:"
echo "  1. Start backend:   cd backend && pip install -r requirements.txt && uvicorn main:app --reload"
echo "  2. Build extension: cd extension && npm install && npm run dev"
echo "  3. Load in Chrome:  chrome://extensions → Developer mode ON → Load unpacked → extension/dist/"
echo
echo "You do NOT need to hand-edit extension/manifest.json. The build injects your"
echo "OAuth client ID and backend host into extension/dist/manifest.json from the"
echo ".env files above. Verify with: bash scripts/lint-manifest.sh"
